### ISSUE TITLE
Fetch repos error

### ISSUE THREAD

**Issue by yansheng836** [chenjiandongx/gitv#1]
工具是挺不错的，但是好像不会配置……

这个
```
  githubOrg:
    - cloneDir: "./db"
      destination: "./db/repos-404pages.yaml"
      token: "ghp_b……"
      #
      #（可选项）排除某些项目
      # excludeRepos:
      #   - "some_repos"
      #
      # yansheng836/404pages
      org: "404pages"  # 拉取的仓库名
      type: "owner"
```
报错信息：
```
$ ./gitv_windows_amd64.exe -f
start to fetch github repos...
fetching github repos page: 1
fetching github repos page: 1
fetching github repos page: 1
Fetch repos error: error decoding response body: invalid type: map, expected a sequence at line 1 column 0
```
